before:
  hooks:
    - go mod download
builds:
  - binary: packetframe-svc-edge
    dir: cmd/server/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
nfpms:
  - id: nfpm-default
    package_name: packetframe-svc-edge
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: Packetframe
    homepage: https://github.com/packetframe/edge
    maintainer: Nate Sales <nate@packetframe.com>
    description: Packetframe edge service
    license: GNU GPL-3.0
    section: utils
    priority: extra
    formats:
      - deb
    contents:
      - src: packetframe-svc-edge.service
        dst: /lib/systemd/system/packetframe-svc-edge.service
